image: alpine

stages:
  - test
  - deploy

before_script:
  - apk --no-cache add py3-pip python3-dev git
  - pip3 install sphinx sphinx_rtd_theme
  - pip3 install pytest coverage

coverage:
  stage: test
  script:
    - coverage run --source=singleton_config -m pytest tests/test_config.py
    - coverage report -m
  coverage: '/^TOTAL.+?(\d+\%)$/'
  only:
  - master

pages:
  stage: deploy
  script:
  - apk --no-cache add make
  - cd docs/
  - make html
  - cd -
  - mv docs/build/html public/
  artifacts:
    paths:
    - public
  only:
  - master
